DROP DATABASE IF EXISTS `pmp`;
CREATE DATABASE `pmp`;
USE `pmp`;

# 고객 정보

CREATE TABLE `member`(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
userid CHAR(100) NOT NULL,
userpw CHAR(150) NOT NULL,
username CHAR(100) NOT NULL,
userlocation CHAR(100) NOT NULL,
userage INT(20) NOT NULL,
usergender CHAR(10) NOT NULL
);

# 서버 정보

CREATE TABLE menu(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
menuname CHAR(100) NOT NULL UNIQUE);

CREATE TABLE location(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
location_name CHAR(100) NOT NULL);

CREATE TABLE shop(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
shopname CHAR(100) NOT NULL,
locationid INT NOT NULL,
CONSTRAINT 
    FOREIGN KEY (locationid) REFERENCES location (id)
    ON DELETE CASCADE
    ON UPDATE RESTRICT);

CREATE TABLES 

SHOW TABLES;

